services:
  mysql:
    image: 'mysql:latest'
    container_name: 'brewmate-mysql'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

  spring:
    build: .
    container_name: 'brewmate-spring'
    depends_on:
      - mysql
    ports:
      - '8081:8081'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'

  adminer:
    image: 'adminer:latest'
    container_name: 'brewmate-adminer'
    ports:
      - '8080:8080'
