services:
  database:
    image: 'mysql:innovation'
    container_name: 'brewmate-database'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

  backend:
    build: ./backend
    container_name: 'brewmate-backend'
    depends_on:
      - database
    ports:
      - '8081:8081'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'

  frontend:
    build: ./frontend
    container_name: 'brewmate-frontend'
    depends_on:
      - backend
    ports:
      - '5173:5173'
    volumes:
      - './frontend:/app'

  adminer:
    image: 'adminer:latest'
    container_name: 'brewmate-adminer'
    ports:
      - '8080:8080'
    depends_on:
      - database
